### ISSUE TITLE
Support searches by filename

### ISSUE THREAD

**Issue by morallo** [blacktop/docker-nsrl#1]
Thx for the project. It would be even cooler if you could lookup filenames

**Comment by blacktop** [comment]
Hmmm, can you give a good use case?  

I deal a lot with malware where filenames are essentially meaningless.  

I am definitely not apposed, just not sure if there is any major benefit.

**Comment by morallo** [comment]
We often have to qualify existing "indicators of compromise" before launching a search all over our computers. 
Sometimes the indicators only include a filename. To prevent false positives, we are interested in knowing if a given filename is used by a legit product.

**Comment by kost** [comment]
Checkout k0st/kfn:
https://registry.hub.docker.com/u/k0st/kfn/

Example:
docker run --rm k0st/kfn notepad.exe

Also for hashes:
docker run --rm k0st/kfh 16f769bc1d37cc14e3093b9881cf1691

Check out:
https://k0st.wordpress.com/2015/06/18/using-bloom-filter-for-hash-database/

**Comment by morallo** [comment]
Nice, I will give it a try :)
